/**
 * Every country / territory with its international calling code, keyed by
 * ISO 3166-1 alpha-2. Territories in the North American Numbering Plan carry
 * their area code too (e.g. Anguilla "+1264"), so a full number can be split
 * back into country + local part. US comes first so it stays the default,
 * and wins the shared "+1" prefix; the rest are alphabetical by country name.
 */
export interface CountryDialCode {
  value: string;
  dial: string;
}

export const COUNTRY_DIAL_CODES: readonly CountryDialCode[] = [
  { value: "US", dial: "+1" },
  { value: "CA", dial: "+1" },
  { value: "AF", dial: "+93" },
  { value: "AX", dial: "+358" },
  { value: "AL", dial: "+355" },
  { value: "DZ", dial: "+213" },
  { value: "AS", dial: "+1684" },
  { value: "AD", dial: "+376" },
  { value: "AO", dial: "+244" },
  { value: "AI", dial: "+1264" },
  { value: "AG", dial: "+1268" },
  { value: "AR", dial: "+54" },
  { value: "AM", dial: "+374" },
  { value: "AW", dial: "+297" },
  { value: "AU", dial: "+61" },
  { value: "AT", dial: "+43" },
  { value: "AZ", dial: "+994" },
  { value: "BS", dial: "+1242" },
  { value: "BH", dial: "+973" },
  { value: "BD", dial: "+880" },
  { value: "BB", dial: "+1246" },
  { value: "BY", dial: "+375" },
  { value: "BE", dial: "+32" },
  { value: "BZ", dial: "+501" },
  { value: "BJ", dial: "+229" },
  { value: "BM", dial: "+1441" },
  { value: "BT", dial: "+975" },
  { value: "BO", dial: "+591" },
  { value: "BQ", dial: "+599" },
  { value: "BA", dial: "+387" },
  { value: "BW", dial: "+267" },
  { value: "BR", dial: "+55" },
  { value: "IO", dial: "+246" },
  { value: "VG", dial: "+1284" },
  { value: "BN", dial: "+673" },
  { value: "BG", dial: "+359" },
  { value: "BF", dial: "+226" },
  { value: "BI", dial: "+257" },
  { value: "CV", dial: "+238" },
  { value: "KH", dial: "+855" },
  { value: "CM", dial: "+237" },
  { value: "KY", dial: "+1345" },
  { value: "CF", dial: "+236" },
  { value: "TD", dial: "+235" },
  { value: "CL", dial: "+56" },
  { value: "CN", dial: "+86" },
  { value: "CX", dial: "+61" },
  { value: "CC", dial: "+61" },
  { value: "CO", dial: "+57" },
  { value: "KM", dial: "+269" },
  { value: "CG", dial: "+242" },
  { value: "CD", dial: "+243" },
  { value: "CK", dial: "+682" },
  { value: "CR", dial: "+506" },
  { value: "CI", dial: "+225" },
  { value: "HR", dial: "+385" },
  { value: "CU", dial: "+53" },
  { value: "CW", dial: "+599" },
  { value: "CY", dial: "+357" },
  { value: "CZ", dial: "+420" },
  { value: "DK", dial: "+45" },
  { value: "DJ", dial: "+253" },
  { value: "DM", dial: "+1767" },
  { value: "DO", dial: "+1809" },
  { value: "EC", dial: "+593" },
  { value: "EG", dial: "+20" },
  { value: "SV", dial: "+503" },
  { value: "GQ", dial: "+240" },
  { value: "ER", dial: "+291" },
  { value: "EE", dial: "+372" },
  { value: "SZ", dial: "+268" },
  { value: "ET", dial: "+251" },
  { value: "FK", dial: "+500" },
  { value: "FO", dial: "+298" },
  { value: "FJ", dial: "+679" },
  { value: "FI", dial: "+358" },
  { value: "FR", dial: "+33" },
  { value: "GF", dial: "+594" },
  { value: "PF", dial: "+689" },
  { value: "GA", dial: "+241" },
  { value: "GM", dial: "+220" },
  { value: "GE", dial: "+995" },
  { value: "DE", dial: "+49" },
  { value: "GH", dial: "+233" },
  { value: "GI", dial: "+350" },
  { value: "GR", dial: "+30" },
  { value: "GL", dial: "+299" },
  { value: "GD", dial: "+1473" },
  { value: "GP", dial: "+590" },
  { value: "GU", dial: "+1671" },
  { value: "GT", dial: "+502" },
  { value: "GG", dial: "+44" },
  { value: "GN", dial: "+224" },
  { value: "GW", dial: "+245" },
  { value: "GY", dial: "+592" },
  { value: "HT", dial: "+509" },
  { value: "HN", dial: "+504" },
  { value: "HK", dial: "+852" },
  { value: "HU", dial: "+36" },
  { value: "IS", dial: "+354" },
  { value: "IN", dial: "+91" },
  { value: "ID", dial: "+62" },
  { value: "IR", dial: "+98" },
  { value: "IQ", dial: "+964" },
  { value: "IE", dial: "+353" },
  { value: "IM", dial: "+44" },
  { value: "IL", dial: "+972" },
  { value: "IT", dial: "+39" },
  { value: "JM", dial: "+1876" },
  { value: "JP", dial: "+81" },
  { value: "JE", dial: "+44" },
  { value: "JO", dial: "+962" },
  { value: "KZ", dial: "+7" },
  { value: "KE", dial: "+254" },
  { value: "KI", dial: "+686" },
  { value: "XK", dial: "+383" },
  { value: "KW", dial: "+965" },
  { value: "KG", dial: "+996" },
  { value: "LA", dial: "+856" },
  { value: "LV", dial: "+371" },
  { value: "LB", dial: "+961" },
  { value: "LS", dial: "+266" },
  { value: "LR", dial: "+231" },
  { value: "LY", dial: "+218" },
  { value: "LI", dial: "+423" },
  { value: "LT", dial: "+370" },
  { value: "LU", dial: "+352" },
  { value: "MO", dial: "+853" },
  { value: "MG", dial: "+261" },
  { value: "MW", dial: "+265" },
  { value: "MY", dial: "+60" },
  { value: "MV", dial: "+960" },
  { value: "ML", dial: "+223" },
  { value: "MT", dial: "+356" },
  { value: "MH", dial: "+692" },
  { value: "MQ", dial: "+596" },
  { value: "MR", dial: "+222" },
  { value: "MU", dial: "+230" },
  { value: "YT", dial: "+262" },
  { value: "MX", dial: "+52" },
  { value: "FM", dial: "+691" },
  { value: "MD", dial: "+373" },
  { value: "MC", dial: "+377" },
  { value: "MN", dial: "+976" },
  { value: "ME", dial: "+382" },
  { value: "MS", dial: "+1664" },
  { value: "MA", dial: "+212" },
  { value: "MZ", dial: "+258" },
  { value: "MM", dial: "+95" },
  { value: "NA", dial: "+264" },
  { value: "NR", dial: "+674" },
  { value: "NP", dial: "+977" },
  { value: "NL", dial: "+31" },
  { value: "NC", dial: "+687" },
  { value: "NZ", dial: "+64" },
  { value: "NI", dial: "+505" },
  { value: "NE", dial: "+227" },
  { value: "NG", dial: "+234" },
  { value: "NU", dial: "+683" },
  { value: "NF", dial: "+672" },
  { value: "KP", dial: "+850" },
  { value: "MK", dial: "+389" },
  { value: "MP", dial: "+1670" },
  { value: "NO", dial: "+47" },
  { value: "OM", dial: "+968" },
  { value: "PK", dial: "+92" },
  { value: "PW", dial: "+680" },
  { value: "PS", dial: "+970" },
  { value: "PA", dial: "+507" },
  { value: "PG", dial: "+675" },
  { value: "PY", dial: "+595" },
  { value: "PE", dial: "+51" },
  { value: "PH", dial: "+63" },
  { value: "PL", dial: "+48" },
  { value: "PT", dial: "+351" },
  { value: "PR", dial: "+1787" },
  { value: "QA", dial: "+974" },
  { value: "RE", dial: "+262" },
  { value: "RO", dial: "+40" },
  { value: "RU", dial: "+7" },
  { value: "RW", dial: "+250" },
  { value: "BL", dial: "+590" },
  { value: "SH", dial: "+290" },
  { value: "KN", dial: "+1869" },
  { value: "LC", dial: "+1758" },
  { value: "MF", dial: "+590" },
  { value: "PM", dial: "+508" },
  { value: "VC", dial: "+1784" },
  { value: "WS", dial: "+685" },
  { value: "SM", dial: "+378" },
  { value: "ST", dial: "+239" },
  { value: "SA", dial: "+966" },
  { value: "SN", dial: "+221" },
  { value: "RS", dial: "+381" },
  { value: "SC", dial: "+248" },
  { value: "SL", dial: "+232" },
  { value: "SG", dial: "+65" },
  { value: "SX", dial: "+1721" },
  { value: "SK", dial: "+421" },
  { value: "SI", dial: "+386" },
  { value: "SB", dial: "+677" },
  { value: "SO", dial: "+252" },
  { value: "ZA", dial: "+27" },
  { value: "KR", dial: "+82" },
  { value: "SS", dial: "+211" },
  { value: "ES", dial: "+34" },
  { value: "LK", dial: "+94" },
  { value: "SD", dial: "+249" },
  { value: "SR", dial: "+597" },
  { value: "SJ", dial: "+47" },
  { value: "SE", dial: "+46" },
  { value: "CH", dial: "+41" },
  { value: "SY", dial: "+963" },
  { value: "TW", dial: "+886" },
  { value: "TJ", dial: "+992" },
  { value: "TZ", dial: "+255" },
  { value: "TH", dial: "+66" },
  { value: "TL", dial: "+670" },
  { value: "TG", dial: "+228" },
  { value: "TK", dial: "+690" },
  { value: "TO", dial: "+676" },
  { value: "TT", dial: "+1868" },
  { value: "TN", dial: "+216" },
  { value: "TR", dial: "+90" },
  { value: "TM", dial: "+993" },
  { value: "TC", dial: "+1649" },
  { value: "TV", dial: "+688" },
  { value: "UG", dial: "+256" },
  { value: "UA", dial: "+380" },
  { value: "AE", dial: "+971" },
  { value: "GB", dial: "+44" },
  { value: "UY", dial: "+598" },
  { value: "VI", dial: "+1340" },
  { value: "UZ", dial: "+998" },
  { value: "VU", dial: "+678" },
  { value: "VA", dial: "+39" },
  { value: "VE", dial: "+58" },
  { value: "VN", dial: "+84" },
  { value: "WF", dial: "+681" },
  { value: "EH", dial: "+212" },
  { value: "YE", dial: "+967" },
  { value: "ZM", dial: "+260" },
  { value: "ZW", dial: "+263" },
];

/**
 * Where several countries share a calling code, the one a bare number with
 * that code is assumed to belong to when it's split back apart.
 */
export const PRIMARY_DIAL_CODE_COUNTRY: Readonly<Record<string, string>> = {
  "+1": "US",
  "+7": "RU",
  "+39": "IT",
  "+44": "GB",
  "+47": "NO",
  "+61": "AU",
  "+212": "MA",
  "+262": "RE",
  "+358": "FI",
  "+590": "GP",
  "+599": "CW",
};
